server:
  port: 8080
  servlet:
    context-path: /exo

spring:
  datasource:
    url: jdbc:mysql://root:ZyZZWJCKpIobyLSbyKppHdnOsuKMAoCD@gondola.proxy.rlwy.net:56298/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ZyZZWJCKpIobyLSbyKppHdnOsuKMAoCD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#  show-actuator: true

