
server:
  port: 8080
  servlet:
    context-path: /exo

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/exo"
    username: root
    password: Tambao@1911
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
