server:
  port: 8080
  servlet:
    context-path: /exo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#  show-actuator: true

