server:
  port: 8080
  servlet:
    context-path: /exo

spring:
  datasource:
    url: jdbc:mysql://root:IdcOaIpCrubjbyqjThowuWMFLzwdbJeF@mysql.railway.internal:3306/railway
    username: root
    password: IdcOaIpCrubjbyqjThowuWMFLzwdbJeF
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

