server:
  port: 8080
  servlet:
    context-path: /exo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

endpoints:
  cors:
    allowed-credentials: false
    allowed-headers: "*"
    allowed-methods:
      - POST
      - PUT
      - GET
      - OPTIONS
      - DELETE
    max-age: 36000
    allowed-origins: "*"


